backend:
  name: github
  repo: SPICExLAB/spice-lab.org
  branch: main
  auth:
    client_id: Ov23li7tmj3HzMHU0YV7
    redirect_uri: https://spicexlab.github.io/spice-lab.org/admin/callback

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "settibgTexts"
    label: "Settings"
    files:
      - name: "homepage"
        label: "Homepage"
        file: "src/content/settingTexts/homepageText.md"
        fields:
          - { label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown" }

  - name: "news"
    label: "News"
    folder: "src/content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Type", name: "type", widget: "hidden", default: "news" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Content", name: "content", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image", required: false }
